repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.0.2
#    hooks:
#      - id: prettier
#        additional_dependencies:
#          - prettier@2.3.2
#        args:
#          - --write
#          - --list-different
#          - --ignore-unknown
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-kotlin
        args: [--autofix]
      - id: pretty-format-java
        args: [--autofix]
